apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: workloads
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
commonLabels:
  app: shopping-cart-svc
  backstage.io/kubernetes-id: shopping-cart-svc
images:
  - name: to-be-replaced
    newName: ghcr.io/nicpym/shopping-cart-svc
    newTag: v0.0.1
